os:
  - linux
sudo: required
language: node_js
node_js:
  - "9.8.0"

addons:
    chrome: stable

cache:
  directories:
    - node_modules

branches:
  only:
    - master
    - develop

before_script:
  - "sudo chown root /opt/google/chrome/chrome-sandbox"
  - "sudo chmod 4755 /opt/google/chrome/chrome-sandbox"
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install -g @angular/cli
  - npm install codecov -g
  - npm install -g codeclimate-test-reporter

script:
  - ng test --watch=false --code-coverage --progress  --colors --single-run
  - ng build --prod

after_success:
  - codecov

notifications:
  email:
    on_failure: change
    on_success: change
