language: node_js
node_js:
  - "6.9"

branches:
  only:
    - master
    - develop

before_script:
  - npm install -g @angular/cli

script:
  - ng build --prod
  - ng test --watch false --code-coverage

#after_success:
#  - firebase deploy --token $FIREBASE_TOKEN

notifications:
  email:
    on_failure: change
    on_success: change
