language: node_js
node_js:
  - "6.9"

branches:
  only:
    - master
    - develop

before_script:
  - npm install -g @angular/cli
  - npm install codecov -g

script:
  - ng test --watch=false --code-coverage --progress  --colors --single-run
  - ng build --prod

#after_success:
#  - firebase deploy --token $FIREBASE_TOKEN

notifications:
  email:
    on_failure: change
    on_success: change
