language: node_js
node_js:
  - "9.8.0"

addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable

cache:
  directories:
    - node_modules

branches:
  only:
    - master
    - develop

before_script:
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install -g @angular/cli
  - npm install codecov -g

script:
  - ng test --watch=false --code-coverage --progress  --colors --single-run
  - ng build --prod

notifications:
  email:
    on_failure: change
    on_success: change
